# Generated by Django 5.0.1 on 2024-01-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homemodel',
            options={'verbose_name': 'home', 'verbose_name_plural': 'homes'},
        ),
    ]
