# Generated by Django 5.0.1 on 2024-01-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_categorymodel_productsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
        migrations.DeleteModel(
            name='ProductsModel',
        ),
    ]
